### ISSUE TITLE
Discrepancy in the analysis of Q4.9 

### ISSUE THREAD

**Issue by InessaPawson** [numpy/user-survey-2020-details#22]
_Of the respondents who expressed interest in contributing to NumPy, most (75%) were interested in contributing to the source code and 47% expressed interest in developing education content or technical documentation._
**Source:** https://rossbar.github.io/numpy-survey-results/content/contributions.html

This is my analysis for Q4.9 (see below). 29% expressed their interest in contributing to the source code and 36% – would like to help with educational content or technical documentation.

<img width="1427" alt="NumPySurvey_Q4 9" src="https://user-images.githubusercontent.com/43481325/103761430-61a2ac00-5062-11eb-86d2-55222acc3762.png">

**Comment by rossbar** [comment]
I think the problem with the above analysis is that it doesn't account for multiple responses. Note that the sum of the counts (1589) is greater than the total number of survey respondents (1236). Instead, I divided by the number of people who responded "Yes" to the "would you be interested in contributing to NumPy" question, which was 608. That's where the numbers in the contributions page come from, e.g. 457 / 608 ~ 75%.

**Comment by InessaPawson** [comment]
Thank you for the explanation, @rossbar! I’ve reviewed the raw data as well. Your analysis is correct.

**Comment by InessaPawson** [comment]
I’m back at it.:)

_... 47% expressed interest in developing education content or technical documentation._

Shouldn’t be 94%?
Here are my calculations:
Sample size - 608
Developing educational content - 297
Writing tech documentation - 277
297 + 277 = 574  ~ 94% of 608

**Comment by rossbar** [comment]
This one is tricky too. Many of the people who expressed an interest in one type of docs *also* expressed interest in the other, so they shouldn't be treated independently. I settled on an average of the two, but I agree that "developing educational content or technical documentation" might be a little misleading. Maybe the wording should be changed to:

> 47% expressed interest in developing educational content and/or technical documentation.

**Comment by InessaPawson** [comment]
I’m somewhat surprised that you decided to no longer differentiate educational content and technical documentation. Throughout the entire questionnaire, in the design of which you actively participated, these were two distinct categories, and the survey participants responded accordingly.
For instance:
_Q3.4 In what way(s) have you contributed to these projects? Please select all that apply._
Developing educational content & narrative documentation - 117
Writing technical documentation (e.g. docstrings, user guide, reference guide) - 175 

_Q4.2 In what capacity have you contributed to NumPy? Please select all that apply._
Writing documentation - 42
Educational materials development - 13

_Q4.9 In what ways would you be interested in contributing to NumPy? Please select all that apply._ 
Developing educational content & narrative documentation (e.g. tutorials) - 297
Writing technical documentation (e.g. docstrings, user guide, reference guide) - 277

If you believe that for the purpose of the survey educational content and technical documentation should be put in the same category, please submit your comment in the draft for the 2021 NumPy survey questionnaire: https://docs.google.com/document/d/1wCyuxll55ZjTR8RLbuGCB1VJkk5yjMMBdaP7glLitQ8. (There are quite a few suggestions already.) For the analysis of the 2020 survey,  I’d be more comfortable treating them as two separate categories.

**Comment by rossbar** [comment]
> I’m somewhat surprised that you decided to no longer differentiate educational content and technical documentation. Throughout the entire questionnaire, in the design of which you actively participated, these were two distinct categories, and the survey participants responded accordingly.

Oh no, I totally agree that they are meaningful distinctions! The reason that I chose this wording for the summary in the text is because I had not taken into account *indivdual* responses, but was only summarizing the number of times a given response appeared. The former is more involved, though more informative. I will add it!

**Comment by rossbar** [comment]
Okay, I've added the analysis in #26. The new, more detailed results can be previewed [here](https://rossbar.github.io/numpy-survey-results/content/contributions.html#interests-of-potential-contributors)

**Comment by rossbar** [comment]
This was addressed in #26
