### ISSUE TITLE
Analysis of Q4.1

### ISSUE THREAD

**Issue by InessaPawson** [numpy/user-survey-2020-details#24]
... _while 88 (7%) have contributed to NumPy specifically._ 
**Source:** https://rossbar.github.io/numpy-survey-results/content/contributions.html

Here are my calculations:
Sample size - 1008
Yes - 88
88 ~  8.73% of 1008

**Comment by rossbar** [comment]
Note that this text will have been removed by #25 . This gives me pause though - maybe I'm misinterpreting how the text from the google doc is to be ported into the notebooks. Please double check me in #25 that I've understood correctly and am replacing the right text!

**Comment by InessaPawson** [comment]
The issue is no longer relevant as the text in question has been removed.
