### ISSUE TITLE
Update Acknowledgements/Glossary for 2021

### ISSUE THREAD

**Issue by rossbar** [numpy/user-survey-2020-details#31]
Check these two pages for 2020-specific info and update accordingly. Ideally we'd be able to just update the wording for 2021, but if that's too much of a change we can always copy the files so that there is a 2020 and a 2021 version.

Thanks @stephaniem2014 for catching this!

**Comment by InessaPawson** [comment]
I've updated the Acknowledgements page (see here: https://github.com/numpy/user-survey-2020-details/pull/39/commits/b76c0f41f323c891fc958b341fa2402b048798b5).
The glossaries are identical for both surveys.
