### ISSUE TITLE
Order bar chart categories in Contribution section

### ISSUE THREAD

**Issue by stephaniem2014** [numpy/user-survey-2020-details#32]
It would be nice if we could order the categories in some of the bar charts in the Contribution section. Specifically, we could order from largest bar to smallest, for the "non-NumPy contributors" group, for the bar charts in the following subsections:

1. OSS Contributions
2. Types of Contributions
3. How did contributors get their start?

**Comment by rossbar** [comment]
This is definitely a good idea and would make these charts more digestible. I don't think it's a blocker for the release so I'm not going to milestone it, but it would indeed be a nice improvement.
