### ISSUE TITLE
Address old comment in contributions section

### ISSUE THREAD

**Issue by stephaniem2014** [numpy/user-survey-2020-details#33]
@rossbar made this comment in 2020; not sure if it needs to be addressed this year.

https://github.com/numpy/user-survey-2020-details/blob/e1b1eb31e3c9862178c5ed8edfd5058c3871be6b/site/content/2021/contributions.md?plain=1#L462

**Comment by rossbar** [comment]
Thanks for pointing this out. I have a suspicion that this is related to the category duplication in #34 as well.
