### ISSUE TITLE
Multiple instances of categories in bar charts with quotes to strip

### ISSUE THREAD

**Issue by stephaniem2014** [numpy/user-survey-2020-details#34]
In certain bar charts, there are doubles of each category and the text have quotes that need to be stripped. I believe this issue exists in a few of the bar charts in the Contributions section and in two of the bar charts in the Usage section. Example in attached photo.

There are also some bar charts that have categories for missing values. I think this only exists in the Contribution section bar charts.

![image](https://user-images.githubusercontent.com/41909646/154196945-287a4811-8e28-49c9-80c8-5b0689439e7f.png)

**Comment by rossbar** [comment]
Nice catch! This definitely looks like a parsing issue.

**Comment by rossbar** [comment]
Hmm I'm not seeing this [in the preview either](https://rossbar.github.io/user-survey-2020-details/content/2021/contributions.html#how-did-contributors-get-their-start)... maybe a windows issue?

The good news is it seems to be resolved, so I will close this. If it crops up again we can reopen this.
