### ISSUE TITLE
Click to show/hide tables collapsing

### ISSUE THREAD

**Issue by stephaniem2014** [numpy/user-survey-2020-details#36]
The size of the "click to show/hide" tables are still large even when collapsed. First example of this is the "Language Preference" table in the Community section. I believe all of these types of tables throughout have the same issue.

**Comment by rossbar** [comment]
I had noticed this as well building locally, but it seems to no longer be an issue with the latest preview: https://rossbar.github.io/user-survey-2020-details/content/2021/priorities.html#documentation

My guess is that something had changed in one of the dependencies like myst-nb or the site theme, but it seems to be fixed now. I will close this as resolved, but if the problem reappears we should reopen and chase down why this was happening.

**Comment by rossbar** [comment]
This cropped up again for me locally so I spent some more time looking into it. I noticed that this happens when updating `docutils` from 0.16 to 0.17. I will report upstream, but just making a note here for others who may run into this.
